### PR TITLE
compatibility with node 0.12

### PR DESCRIPTION
**Pull request by nchaulet**
Fix issue #23

### CODE REVIEW

**Comment by nchaulet** [comment]
up :)

**Comment by nchaulet** [comment]
up ?

**Comment by ErisDS** [comment]
Sorry this got lost in the sea of notifications :surfer:

**Comment by nchaulet** [comment]
No problems :) thanks for the merge

On Mon, Jun 22, 2015 at 11:38 AM, Hannah Wolfe <notifications@github.com>
wrote:

> Sorry this got lost in the sea of notifications [image: :surfer:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TryGhost/Ghost-App/pull/24#issuecomment-114051346>.
>



-- 
Nicolas Chaulet (*Développeur Web)*

*Contact :*

    tél : 07 62 16 39 38
    mail : n.chaulet@gmail.com
    twitter : @n_chaulet <https://twitter.com/n_chaulet>

**Pull request merged**
